export const LOAD_STUDIOS_REQUEST = 'LOAD_STUDIOS_REQUEST';
export const LOAD_STUDIOS_SUCCESS = 'LOAD_STUDIOS_SUCCESS';
export const LOAD_STUDIOS_FAIL = 'LOAD_STUDIOS_FAIL';
export const ADD_FILTER_TAG = 'ADD_FILTER_TAG';
export const REMOVE_FILTER_TAG = 'REMOVE_FILTER_TAG';
export const SET_FILTER_TEXT = 'SET_FILTER_TEXT';
export const SET_FILTER_RANGE = 'SET_FILTER_RANGE';
