export const LOAD_STUDIOS_REQUEST = 'LOAD_STUDIOS_REQUEST';
export const LOAD_STUDIOS_SUCCESS = 'LOAD_STUDIOS_SUCCESS';
export const LOAD_STUDIOS_FAIL = 'LOAD_STUDIOS_FAIL';
export const ADD_STUDIOS_FILTER_TAG = 'ADD_STUDIOS_FILTER_TAG';
export const REMOVE_STUDIOS_FILTER_TAG = 'REMOVE_STUDIOS_FILTER_TAG';
export const SET_STUDIOS_FILTER_TEXT = 'SET_STUDIOS_FILTER_TEXT';
export const SET_STUDIOS_PRICE_RANGE = 'SET_STUDIOS_PRICE_RANGE';
